# version: "3.9"
services:
  db:
    # hostname: db
    build: ./db
      # context: ./db
      # dockerfile: db.Dockerfile
    restart: always
    environment:
      POSTGRES_DB: docker
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
      - "5555:5432"
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"